repos:
  # -------------------------------
  # Code formatters
  # -------------------------------
  - repo: https://github.com/psf/black
    rev: 24.8.0   # pin to latest stable release
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9   # match your ruff version
    hooks:
      - id: ruff
        args: [--fix]

  # - repo: https://github.com/myint/docformatter
  #   rev: v1.7.5
  #   hooks:
  #     - id: docformatter
  #       args: ["--in-place", "--wrap-summaries", "88", "--wrap-descriptions", "88"]

  # -------------------------------
  # Type checking
  # -------------------------------
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        additional_dependencies: []   # e.g., ["types-requests"]

  # -------------------------------
  # Security checks
  # -------------------------------
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args: ["-r", "."]

  - repo: https://github.com/pyupio/safety
    rev: 3.2.14
    hooks:
      - id: safety
        args: ["check", "--full-report"]

  # -------------------------------
  # Pre-commit hooks meta
  # -------------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-ast
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace
