version: "3.9"

services:
  redis:
    image: redis:7.4
    container_name: redis_local
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: >
      redis-server
      --appendonly yes
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    volumes:
      - ./data:/data
